
/****** Object:  Database [Categories]    Script Date: 22/12/2020 02:32:49 ******/
CREATE DATABASE [Categories]

ALTER DATABASE [Categories] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Categories].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Categories] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Categories] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Categories] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Categories] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Categories] SET ARITHABORT OFF 
GO
ALTER DATABASE [Categories] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Categories] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Categories] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Categories] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Categories] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Categories] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Categories] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Categories] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Categories] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Categories] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Categories] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Categories] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Categories] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Categories] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Categories] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Categories] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Categories] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Categories] SET RECOVERY FULL 
GO
ALTER DATABASE [Categories] SET  MULTI_USER 
GO
ALTER DATABASE [Categories] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Categories] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Categories] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Categories] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Categories] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'Categories', N'ON'
GO
ALTER DATABASE [Categories] SET QUERY_STORE = OFF
GO
USE [Categories]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
USE [Categories]
GO
/****** Object:  Table [dbo].[Categories]    Script Date: 22/12/2020 02:32:50 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Categories](
	[CategoryID] [bigint] IDENTITY(1,1) NOT NULL,
	[ParentCategoryID] [bigint] NULL,
	[CategoryName] [nvarchar](200) NULL,
 CONSTRAINT [PK_Categories] PRIMARY KEY CLUSTERED 
(
	[CategoryID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Categories] ON 
GO
INSERT [dbo].[Categories] ([CategoryID], [ParentCategoryID], [CategoryName]) VALUES (1, 0, N'Category A')
GO
INSERT [dbo].[Categories] ([CategoryID], [ParentCategoryID], [CategoryName]) VALUES (2, 0, N'Category B')
GO
INSERT [dbo].[Categories] ([CategoryID], [ParentCategoryID], [CategoryName]) VALUES (3, 1, N'Sub Category A')
GO
INSERT [dbo].[Categories] ([CategoryID], [ParentCategoryID], [CategoryName]) VALUES (4, 3, N'Sub Sub Category A')
GO
INSERT [dbo].[Categories] ([CategoryID], [ParentCategoryID], [CategoryName]) VALUES (5, 1, N'Sub Category A2')
GO
INSERT [dbo].[Categories] ([CategoryID], [ParentCategoryID], [CategoryName]) VALUES (6, 1, N'Sub Category A3')
GO
INSERT [dbo].[Categories] ([CategoryID], [ParentCategoryID], [CategoryName]) VALUES (7, 0, N'Category C')
GO
SET IDENTITY_INSERT [dbo].[Categories] OFF
GO

ALTER DATABASE [Categories] SET  READ_WRITE 
GO
