//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CategoriesPanels.Models
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class Category
    {
        public long CategoryID { get; set; }
        public Nullable<long> ParentCategoryID { get; set; }
        public string CategoryName { get; set; }
        public IEnumerable<SelectListItem> ParentCategoryList { get; set; }
        public IEnumerable<SelectListItem> DefaultCategoryList { get; set; }
    }

       
    
}
